### ISSUE TITLE
Add content for d3

### ISSUE THREAD

**Issue by aragilar** [MQ-software-carpentry/2018-07-03-resbaz-python-advanced#3]
- [x] instructors
- [x] helpers
- [x] software
- [x] syllabus (see https://github.com/MQ-software-carpentry/2018-07-03-resbaz-python-advanced/edit/gh-pages/_includes/sc/syllabus.html)

**Comment by Spaxe** [comment]
@aragilar The content I am adopting from is here: https://github.com/MQ-software-carpentry/D3-visualising-data. 

I will also be making sure a descriptive page of the D3 course is available by Tuesday.
