### ISSUE TITLE
Add content for python data analysis

### ISSUE THREAD

**Issue by aragilar** [MQ-software-carpentry/2018-07-03-resbaz-python-advanced#4]
- [ ] instructors
- [ ] helpers
- [ ] software
- [ ] syllabus (see https://github.com/MQ-software-carpentry/2018-07-03-resbaz-python-advanced/edit/gh-pages/_includes/sc/syllabus.html)

**Comment by tasospap21** [comment]
Data Manipulation and Visualisation has been updated.
